[phases.setup]
nixPackages = ["nodejs_18"]

[phases.install]
cmds = [
  "npm --prefix app install",
  "npm --prefix web install"
]

[phases.build]
cmds = [
  "npm --prefix app run build:web"
]

[start]
cmd = "npm --prefix web start"
